// <auto-generated />
using System;
using Int_Err_Count.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Int_Err_Count.Migrations
{
    [DbContext(typeof(UserDbContext))]
    [Migration("20250623025955_addPK")]
    partial class addPK
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Int_Err_Count.Models.ErrorCount", b =>
                {
                    b.Property<string>("Id_Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ASN_Integration_Hamble_ASN")
                        .HasColumnType("int");

                    b.Property<int>("ASN_Integration_SV_ASN")
                        .HasColumnType("int");

                    b.Property<int>("AgileVeeva_Integration_All_Exceptions")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("EBS3PLIntegration_ID_Salesorder_Reprocessing")
                        .HasColumnType("int");

                    b.Property<int>("EBS3PLIntegration_TR_Salesorder_Reprocessing")
                        .HasColumnType("int");

                    b.Property<int>("EBSHungaryIntegrations_HTA_Files")
                        .HasColumnType("int");

                    b.Property<int>("EBSJDA_Integration_UK_All_Exceptions")
                        .HasColumnType("int");

                    b.Property<int>("EBSJDA_Integration_US_All_Exceptions")
                        .HasColumnType("int");

                    b.Property<int>("EBSMAST3PLIntegration_INVONHANDFromMY3PLTOEBS")
                        .HasColumnType("int");

                    b.Property<int>("EBSPTBIntegration_Inspection_EBS_to_SAMM")
                        .HasColumnType("int");

                    b.Property<int>("EDICOM_MX_Invoice_Inbound")
                        .HasColumnType("int");

                    b.Property<int>("EDICOM_MY_All_Exceptions")
                        .HasColumnType("int");

                    b.Property<int>("GPSIntegrations_UK_All_Exceptions")
                        .HasColumnType("int");

                    b.Property<int>("GPSIntegrations_US_All_Exceptions")
                        .HasColumnType("int");

                    b.Property<int>("HCMIntegration_All_Exceptions")
                        .HasColumnType("int");

                    b.Property<int>("JDAKNAPPIntegration_JDA_KNAPP")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MASTIntegration_MY_Invoice")
                        .HasColumnType("int");

                    b.Property<int>("MASTIntegration_MY_LotReprocessing")
                        .HasColumnType("int");

                    b.Property<int>("MASTIntegration_MY_Salesorder_Reprocessing")
                        .HasColumnType("int");

                    b.Property<int>("MASTIntegration_SG_Invoice")
                        .HasColumnType("int");

                    b.Property<int>("MASTIntegration_SG_Salesorder_Reprocessing")
                        .HasColumnType("int");

                    b.Property<int>("MASTIntegration_Shipment")
                        .HasColumnType("int");

                    b.Property<int>("OneCIntegration_All_Exceptions")
                        .HasColumnType("int")
                        .HasColumnName("1CIntegration_All_Exceptions");

                    b.Property<int>("OneVision_B2BASN")
                        .HasColumnType("int");

                    b.Property<int>("RPIntegration_Inventory_Adjustment")
                        .HasColumnType("int");

                    b.Property<int>("RPIntegration_Inventory_Reconcilation")
                        .HasColumnType("int");

                    b.Property<int>("RPIntegration_Inventory_Transefer")
                        .HasColumnType("int");

                    b.Property<int>("RPIntegration_LotReprocessing")
                        .HasColumnType("int");

                    b.Property<int>("RPIntegration_Receipt_Authorization")
                        .HasColumnType("int");

                    b.Property<int>("RPIntegration_Salesorder_Reprocessing")
                        .HasColumnType("int");

                    b.Property<int>("RPIntegration_US_ExceptionReport")
                        .HasColumnType("int");

                    b.Property<int>("SFDC_All_Exceptions")
                        .HasColumnType("int");

                    b.Property<int>("Visidot_Integration_JDADP")
                        .HasColumnType("int");

                    b.HasKey("Id_Name");

                    b.ToTable("ErrorCount");
                });
#pragma warning restore 612, 618
        }
    }
}
