// <auto-generated />
using System;
using Int_Err_Count.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Int_Err_Count.Migrations
{
    [DbContext(typeof(UserDbContext))]
    [Migration("20250622172011_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Int_Err_Count.Models.ErrorCount", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("MASTIntegration_Shipment")
                        .HasColumnType("int");

                    b.Property<int>("OneVision_B2BASN")
                        .HasColumnType("int");

                    b.Property<int>("RPIntegration_US_ExceptionReport")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ErrorCount");
                });
#pragma warning restore 612, 618
        }
    }
}
